### ISSUE TITLE
Docker compose fails to bring up web_1

### ISSUE THREAD

**Issue by haarts** [blockchain-certificates/cert-viewer#41] opened 2016-11-10 11:00 UTC
I'm having an issue running `docker-compose up`:

```
web_1            | Traceback (most recent call last):
web_1            |   File "/cert-viewer/run.py", line 29, in <module>
web_1            |     main()
web_1            |   File "/cert-viewer/run.py", line 20, in main
web_1            |     cert_viewer.set_cert_store(conf)
web_1            |   File "/cert-viewer/cert_viewer/__init__.py", line 17, in set_cert_store
web_1            |     from cert_store.certificate_store import CertificateStore
web_1            |   File "/usr/local/lib/python2.7/dist-packages/cert_store/__init__.py", line 9, in <module>
web_1            |     logging.config.fileConfig('logging.conf')
web_1            | AttributeError: 'module' object has no attribute 'config'
certviewer_web_1 exited with code 1
```

Looks like a Python2/Python3 issue?

**Comment by kimdhamilton** [comment] 2016-11-10 19:17
Thank you @haarts -- I'm looking into this

**Comment by kimdhamilton** [comment] 2016-11-10 21:14
The problem was that the cert-store dependency was updated and cert-viewer was using '>=' in requirements.txt, but wasn't yet equipped to handle the changes. This should be fixed in the latest commit. 

I confirmed locally, but please let me know if you have any problems.

**Comment by kimdhamilton** [comment] 2016-12-02 19:06
this has been resolved

**Closed by kimdhamilton** 2016-12-02 19:06 UTC
